apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gluster-default-sc
parameters:
  restauthenabled: "true"
  resturl: http://10.244.1.236:8080
  restuser: admin
  restuserkey: My Secret
  volumetype: none
provisioner: kubernetes.io/glusterfs
reclaimPolicy: Delete
volumeBindingMode: Immediate