apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: device-communication
  namespace: demonstrator
spec:
  maxReplicas: 5
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: device-communication
  targetCPUUtilizationPercentage: 50